// Generated by SHIVA-1 cad_generator - parametric OpenSCAD model
// Units: millimetres.
// domain: cosmic_habitat
// material: CFRP unidirectional (fibre direction)
scale_note = "1:1000 model";
R = 171;
W = 190;
h = 20;
hull_t = 0.8;
spokes = 6;
union() {
  rotate_extrude($fn = 240) translate([R - h, -W / 2]) difference() { square([h, W]); translate([hull_t, hull_t]) square([h - 2 * hull_t, W - 2 * hull_t]); }
  cylinder(r = 0.08 * R + 2, h = W / 2, center = true, $fn = 64);
  for (j = [0 : spokes - 1]) rotate([0, 0, 360 * j / spokes]) translate([0.08 * R, 0, 0]) rotate([0, 90, 0]) cylinder(r = max(0.01 * R, 0.8), h = R - h - 0.08 * R, $fn = 16);
}
