// Generated by SHIVA-1 cad_generator - parametric OpenSCAD model
// Units: millimetres.
// domain: cosmic_lightsail
// material: Polyimide film (Kapton HN)
scale_note = "1:100 model";
side = 4434.32;
film_t = 0.4;
boom_r = 17.7373;
union() {
  cube([side, side, film_t], center = true);
  for (a = [45, 135]) rotate([0, 0, a]) translate([-side / sqrt(2), 0, 1]) rotate([0, 90, 0]) cylinder(r = boom_r, h = 2 * side / sqrt(2), $fn = 16);
  translate([0, 0, 0.02 * side + 1]) cube([0.06 * side, 0.06 * side, 0.04 * side], center = true);
}
