// Generated by SHIVA-1 cad_generator - parametric OpenSCAD model
// Units: millimetres.
// domain: drone_frame
// material: Aluminium 6061-T6
n_arms = 3;
arm_length = 310;
arm_od = 28;
arm_wall = 1.5;
prop_diameter = 381;
plate_r = 93;
plate_t = 3;
show_props = false;
union() {
  rotate([0, 0, 180 / n_arms]) cylinder(r = plate_r, h = plate_t, center = true, $fn = n_arms);
  for (k = [0 : n_arms - 1]) rotate([0, 0, 360 * k / n_arms]) {
    translate([0.25 * arm_length, 0, 0]) rotate([0, 90, 0])
      difference() { cylinder(d = arm_od, h = 0.75 * arm_length, $fn = 32); translate([0, 0, -1]) cylinder(d = arm_od - 2 * arm_wall, h = arm_length, $fn = 32); }
    translate([arm_length, 0, arm_od / 2]) cylinder(r = 0.07 * prop_diameter + 6, h = 18, $fn = 48);
    if (show_props) %translate([arm_length, 0, arm_od / 2 + 20]) cylinder(d = prop_diameter, h = 1, $fn = 96);
  }
}
