// Generated by SHIVA-1 cad_generator - parametric OpenSCAD model
// Units: millimetres.
// domain: energy_flywheel
// material: Aluminium 7075-T6
R = 641;
bore = 83.8619;
thickness = 400;
hub_r = 50.3171;
shaft_r = 10;
union() {
  difference() { cylinder(r = R, h = thickness, center = true, $fn = 180); cylinder(r = bore, h = thickness + 2, center = true, $fn = 120); }
  if (bore > hub_r) difference() { cylinder(r = bore + 0.5, h = 0.3 * thickness, center = true, $fn = 120); cylinder(r = hub_r - 0.5, h = thickness, center = true, $fn = 96); }
  difference() { cylinder(r = hub_r, h = 1.2 * thickness, center = true, $fn = 96); cylinder(r = shaft_r, h = 2 * thickness, center = true, $fn = 48); }
}
