// Generated by SHIVA-1 cad_generator - parametric OpenSCAD model
// Units: millimetres.
// domain: gear_pair
// material: Alloy steel 4140 (Q&T)
module_mm = 2;
z1 = 40;
z2 = 120;
pressure_angle = 20;
shift = 0.35;
face_width = 28;
bore1 = 12;
bore2 = 36;
// involute geometry evaluated in OpenSCAD (degrees)
function inv_deg(a) = (tan(a) - a * PI / 180) * 180 / PI;
function polar(r, t) = [r * cos(t), r * sin(t)];
module involute_gear(m, z, pa, x, width, bore, steps = 12) {
  rp = m * z / 2; rb = rp * cos(pa); ra = rp + m * (1 + x); rf = rp - m * (1.25 - x);
  half_p = (90 + 2 * x * tan(pa) * 180 / PI) / z;
  r0 = max(rb, rf);
  rs = [for (i = [0 : steps]) r0 + (ra - r0) * i / steps];
  function theta(r) = half_p + inv_deg(pa) - inv_deg(acos(min(1, rb / r)));
  pts = [for (k = [0 : z - 1]) let(c = k * 360 / z) each concat(
           [polar(rf, c - theta(r0))],
           [for (r = rs) polar(r, c - theta(r))],
           [for (i = [steps : -1 : 0]) polar(rs[i], c + theta(rs[i]))],
           [polar(rf, c + theta(r0))])];
  difference() {
    linear_extrude(height = width) polygon(pts);
    translate([0, 0, -1]) cylinder(r = bore, h = width + 2, $fn = 48);
  }
}
involute_gear(module_mm, z1, pressure_angle, shift, face_width, bore1);
translate([module_mm * (z1 + z2) / 2, 0, 0]) rotate([0, 0, (z2 % 2 == 0) ? 180 / z2 : 0])
  involute_gear(module_mm, z2, pressure_angle, -shift, face_width, bore2);
