// Generated by SHIVA-1 cad_generator - parametric OpenSCAD model
// Units: millimetres.
// domain: generative_bracket
pixel = 5;
thickness = 6;
// CPPN-NEAT generated bracket (run-length merged pixels)
union() {
  translate([0.000, 15.000, 0]) cube([55.000, 5.000, thickness]);
  translate([0.000, 20.000, 0]) cube([100.000, 5.000, thickness]);
  translate([0.000, 25.000, 0]) cube([160.000, 5.000, thickness]);
  translate([0.000, 30.000, 0]) cube([80.000, 5.000, thickness]);
  translate([95.000, 30.000, 0]) cube([65.000, 5.000, thickness]);
  translate([0.000, 35.000, 0]) cube([70.000, 5.000, thickness]);
  translate([115.000, 35.000, 0]) cube([45.000, 5.000, thickness]);
  translate([0.000, 40.000, 0]) cube([70.000, 5.000, thickness]);
  translate([115.000, 40.000, 0]) cube([45.000, 5.000, thickness]);
  translate([0.000, 45.000, 0]) cube([80.000, 5.000, thickness]);
  translate([95.000, 45.000, 0]) cube([65.000, 5.000, thickness]);
  translate([0.000, 50.000, 0]) cube([160.000, 5.000, thickness]);
  translate([0.000, 55.000, 0]) cube([100.000, 5.000, thickness]);
  translate([0.000, 60.000, 0]) cube([55.000, 5.000, thickness]);
}
