// Generated by SHIVA-1 cad_generator - parametric OpenSCAD model
// Units: millimetres.
// domain: structure_truss
// material: CFRP quasi-isotropic laminate
r_top = 7;
r_bottom = 11.5;
r_web = 8;
joint_r = 18.4;
nodes = [[0.000,0.000],[666.667,0.000],[1333.333,0.000],[2000.000,0.000],[0.000,985.000],[666.667,755.000],[1333.333,400.000]];
members = [[0,1,1],[1,2,1],[2,3,1],[4,5,0],[5,6,0],[6,3,0],[1,5,2],[2,6,2],[4,1,2],[5,2,2]];
radii = [r_top, r_bottom, r_web];
module bar(a, b, r) { hull() { translate([a[0], 0, a[1]]) sphere(r = r, $fn = 24);
                                  translate([b[0], 0, b[1]]) sphere(r = r, $fn = 24); } }
union() {
  for (m = members) bar(nodes[m[0]], nodes[m[1]], radii[m[2]]);
  for (n = nodes) translate([n[0], 0, n[1]]) sphere(r = joint_r, $fn = 32);
}
